name: cross-test

on:
  workflow_call:

jobs:
  macos-x64:
    uses: ./.github/workflows/cross-pair.yml
    with:
      build_os: macos-15
      test_os: macos-15-intel
      target_triple: x86_64-apple-darwin
      target_name: x64-macos-darwin
      asset_name: clice-x64-macos-darwin.tar.gz

  linux-arm64:
    uses: ./.github/workflows/cross-pair.yml
    with:
      build_os: ubuntu-24.04
      test_os: ubuntu-24.04-arm
      target_triple: aarch64-linux-gnu
      target_name: arm64-linux-gnu
      pixi_env: cross-linux-arm64
      asset_name: clice-arm64-linux-gnu.tar.gz

  windows-arm64:
    uses: ./.github/workflows/cross-pair.yml
    with:
      build_os: windows-2025
      test_os: windows-11-arm
      target_triple: aarch64-pc-windows-msvc
      target_name: arm64-windows-msvc
      asset_name: clice-arm64-windows-msvc.zip
      pixi_env: cross-windows-arm64
