name: publish docs

on:
  workflow_call:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: clice-io/docs@main
        with:
          project: clice
          token: ${{ secrets.PUBLISH_DOCS }}
